//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKKApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DKKEntities : DbContext
    {
        public DKKEntities()
            : base("name=DKKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Curators> tbl_Curators { get; set; }
        public virtual DbSet<tbl_Documents> tbl_Documents { get; set; }
        public virtual DbSet<tbl_DocumentTypes> tbl_DocumentTypes { get; set; }
        public virtual DbSet<tbl_EducationLevels> tbl_EducationLevels { get; set; }
        public virtual DbSet<tbl_Proprieties> tbl_Proprieties { get; set; }
        public virtual DbSet<tbl_Schools> tbl_Schools { get; set; }
        public virtual DbSet<tbl_SchoolTypes> tbl_SchoolTypes { get; set; }
    }
}
