//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKKApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Documents
    {
        public int DocumentID { get; set; }
        public Nullable<int> DocumentTypeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string FatherName { get; set; }
        public string YearBorn { get; set; }
        public string YearComplete { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public string Series { get; set; }
        public string DocNumber { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public string IDNumber { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual tbl_DocumentTypes tbl_DocumentTypes { get; set; }
        public virtual tbl_Schools tbl_Schools { get; set; }
    }
}
