//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKKApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Schools
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Schools()
        {
            this.tbl_Documents = new HashSet<tbl_Documents>();
        }
    
        public int SchoolID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Name { get; set; }
        public string YearFrom { get; set; }
        public string YearTo { get; set; }
        public Nullable<int> ProprietyID { get; set; }
        public Nullable<int> CuratorID { get; set; }
        public string Locality { get; set; }
        public string Obl { get; set; }
        public string Rajon { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> NDoc { get; set; }
    
        public virtual tbl_Curators tbl_Curators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Documents> tbl_Documents { get; set; }
        public virtual tbl_Proprieties tbl_Proprieties { get; set; }
        public virtual tbl_SchoolTypes tbl_SchoolTypes { get; set; }
    }
}
